import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useQuery } from "urql";
import Product from "@/components/product";
import { PRODUCT_QUERY } from "@/util/query";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  //FETCH PRODUCTS FROM STRAPI
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;
  
  if (fetching) return <h1>Loading...</h1>;
  if (error) return <h1>Oh no... {error.message}</h1>

  const products = data.products.data;
  console.log(products);
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Hello react</h1>
        <div className="products">
          {products.map((product) => <Product key={product.attributes.slug} product={product}/>)}
        </div>
      </main>
    </>
  );
}
