import Head from "next/head";
import { Inter } from "@next/font/google";
import { useQuery } from "urql";
import Product from "@/components/product";
import { PRODUCT_QUERY } from "@/util/query";

//styled components
import { Products } from "@/styles/product_styles";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  //FETCH PRODUCTS FROM STRAPI
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;
  
  if (fetching) return <h1>Loading...</h1>;
  if (error) return <h1>Oh no... {error.message}</h1>

  const products = data.products.data;
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello react</h1>
        <Products>
          {products.map((product) => <Product key={product.attributes.slug} product={product}/>)}
        </Products>
      </main>
    </>
  );
}
