export const PRODUCT_QUERY = `
query{
    products{
      data{
        attributes{
          title
          description
          slug
          image{
            data{
              attributes{
                formats
              }
            }
          }
        }
      }
    }
  }
`;
